apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-reverser
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ip-reverser
          image: 735265414519.dkr.ecr.eu-west-1.amazonaws.com/dev-ip-reverser:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi