apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-reverser
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-cluster
    alb.ingress.kubernetes.io/subnets: subnet-0586bb8cb10342c1f, subnet-0c674e90780e0fcc8
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=dev-rentrahisi-eks-cluster-alb-access-logs,idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=5
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=devops
    alb.ingress.kubernetes.io/group.name: dev
spec:
  ingressClassName: alb
  rules:
    - host: ip-reverser.rentrahisi.co.ke
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip-reverser
                port:
                  number: 8080