apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-reverser
  annotations:
    secret.reloader.stakater.com/reload: "app-secrets"
  labels:
    app: ip-reverser
spec:
  selector:
    matchLabels:
      app: ip-reverser
  template:
    metadata:
      labels:
        app: ip-reverser
    spec:
      serviceAccountName: ip-reverser
      containers:
        - name: ip-reverser
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          envFrom:
            - secretRef:
                name: app-secrets