apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ip-reverser
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ip-reverser
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300